# Generated by Django 5.0.6 on 2024-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='socialmedia', max_length=100),
            preserve_default=False,
        ),
    ]
